// <auto-generated />
using System;
using Hotel.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hotel.DataAccess.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hotel.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WiFi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TV"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AC"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mini Bar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jacuzzi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Balcony"
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Entities.CheckInRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProcessedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("CheckInRecords");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.CheckOutRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProcessedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("CheckOutRecords");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.HotelSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HotelSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Standard check-in time",
                            Key = "CheckInTime",
                            Value = "14:00"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standard check-out time",
                            Key = "CheckOutTime",
                            Value = "11:00"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Default currency",
                            Key = "Currency",
                            Value = "USD"
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Entities.HousekeepingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("RoomId");

                    b.ToTable("HousekeepingTasks");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("RoomId");

                    b.ToTable("MaintenanceTickets");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Guests")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Client"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reception"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Housekeeping"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("numeric");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            Description = "Cozy single room with modern amenities",
                            Floor = 1,
                            IsActive = true,
                            Number = "101",
                            PricePerNight = 89m,
                            RoomTypeId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1,
                            Description = "Cozy single room with modern amenities",
                            Floor = 1,
                            IsActive = true,
                            Number = "102",
                            PricePerNight = 89m,
                            RoomTypeId = 1,
                            Status = "Occupied"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2,
                            Description = "Spacious double room with city view",
                            Floor = 1,
                            IsActive = true,
                            Number = "103",
                            PricePerNight = 129m,
                            RoomTypeId = 2,
                            Status = "Dirty"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2,
                            Description = "Spacious double room with city view",
                            Floor = 2,
                            IsActive = true,
                            Number = "201",
                            PricePerNight = 129m,
                            RoomTypeId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            Description = "Luxury suite with separate living area",
                            Floor = 2,
                            IsActive = true,
                            Number = "202",
                            PricePerNight = 249m,
                            RoomTypeId = 3,
                            Status = "Occupied"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 2,
                            Description = "Spacious double room with city view",
                            Floor = 2,
                            IsActive = true,
                            Number = "203",
                            PricePerNight = 129m,
                            RoomTypeId = 2,
                            Status = "Cleaning"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 3,
                            Description = "Deluxe room with premium amenities",
                            Floor = 3,
                            IsActive = true,
                            Number = "301",
                            PricePerNight = 189m,
                            RoomTypeId = 4,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 4,
                            Description = "Luxury suite with separate living area",
                            Floor = 3,
                            IsActive = true,
                            Number = "302",
                            PricePerNight = 249m,
                            RoomTypeId = 3,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 3,
                            Description = "Deluxe room with premium amenities",
                            Floor = 3,
                            IsActive = true,
                            Number = "303",
                            PricePerNight = 189m,
                            RoomTypeId = 4,
                            Status = "OutOfOrder"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 2,
                            Description = "Spacious double room with city view",
                            Floor = 3,
                            IsActive = true,
                            Number = "304",
                            PricePerNight = 129m,
                            RoomTypeId = 2,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Entities.RoomAmenity", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.HasKey("RoomId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("RoomAmenities");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 1,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 2,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 2,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 3,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 3,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 3,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 4,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 4,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 4,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 5,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 5,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 5,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 6,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 6,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 6,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 7,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 7,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 7,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 8,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 8,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 8,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 9,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 9,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 9,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 10,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomId = 10,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomId = 10,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomId = 5,
                            AmenityId = 4
                        },
                        new
                        {
                            RoomId = 5,
                            AmenityId = 5
                        },
                        new
                        {
                            RoomId = 5,
                            AmenityId = 6
                        },
                        new
                        {
                            RoomId = 8,
                            AmenityId = 4
                        },
                        new
                        {
                            RoomId = 8,
                            AmenityId = 5
                        },
                        new
                        {
                            RoomId = 8,
                            AmenityId = 6
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 89m,
                            Description = "Cozy single room",
                            Name = "single"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 129m,
                            Description = "Spacious double room",
                            Name = "double"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 249m,
                            Description = "Luxury suite",
                            Name = "suite"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 189m,
                            Description = "Deluxe room",
                            Name = "deluxe"
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@smarthotel.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$s5EGEu.A.g4E6QhP1p4C5OTtG0gq6g.0ZJ/E9fM9zMOhWdXXe4/lO",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "guest@example.com",
                            FirstName = "Guest",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$s5EGEu.A.g4E6QhP1p4C5OTtG0gq6g.0ZJ/E9fM9zMOhWdXXe4/lO",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@hotel.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$s5EGEu.A.g4E6QhP1p4C5OTtG0gq6g.0ZJ/E9fM9zMOhWdXXe4/lO",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@hotel.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Smith",
                            PasswordHash = "$2a$11$s5EGEu.A.g4E6QhP1p4C5OTtG0gq6g.0ZJ/E9fM9zMOhWdXXe4/lO",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tom@hotel.com",
                            FirstName = "Tom",
                            IsActive = true,
                            LastName = "Martinez",
                            PasswordHash = "$2a$11$s5EGEu.A.g4E6QhP1p4C5OTtG0gq6g.0ZJ/E9fM9zMOhWdXXe4/lO",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "robert@hotel.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$s5EGEu.A.g4E6QhP1p4C5OTtG0gq6g.0ZJ/E9fM9zMOhWdXXe4/lO",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emily@hotel.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "$2a$11$s5EGEu.A.g4E6QhP1p4C5OTtG0gq6g.0ZJ/E9fM9zMOhWdXXe4/lO",
                            RoleId = 6
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Entities.CheckInRecord", b =>
                {
                    b.HasOne("Hotel.Domain.Entities.User", "ProcessedBy")
                        .WithMany("ProcessedCheckIns")
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel.Domain.Entities.Reservation", "Reservation")
                        .WithOne("CheckInRecord")
                        .HasForeignKey("Hotel.Domain.Entities.CheckInRecord", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedBy");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.CheckOutRecord", b =>
                {
                    b.HasOne("Hotel.Domain.Entities.User", "ProcessedBy")
                        .WithMany("ProcessedCheckOuts")
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel.Domain.Entities.Reservation", "Reservation")
                        .WithOne("CheckOutRecord")
                        .HasForeignKey("Hotel.Domain.Entities.CheckOutRecord", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedBy");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.HousekeepingTask", b =>
                {
                    b.HasOne("Hotel.Domain.Entities.User", "AssignedTo")
                        .WithMany("HousekeepingTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hotel.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.HasOne("Hotel.Domain.Entities.User", "AssignedTo")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hotel.Domain.Entities.User", "ReportedBy")
                        .WithMany("ReportedTickets")
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("ReportedBy");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Hotel.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Room", b =>
                {
                    b.HasOne("Hotel.Domain.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.RoomAmenity", b =>
                {
                    b.HasOne("Hotel.Domain.Entities.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel.Domain.Entities.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.User", b =>
                {
                    b.HasOne("Hotel.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("CheckInRecord");

                    b.Navigation("CheckOutRecord");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.Room", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Hotel.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("HousekeepingTasks");

                    b.Navigation("ProcessedCheckIns");

                    b.Navigation("ProcessedCheckOuts");

                    b.Navigation("ReportedTickets");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
